// <auto-generated />
using lite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171113142746_DodanyProjekt")]
    partial class DodanyProjekt
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lite.Models.ExternalGrid", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double?>("ActivePower");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NodeNo");

                    b.Property<string>("NodeType")
                        .IsRequired();

                    b.Property<double?>("ReactivePower");

                    b.Property<double?>("VoltageAngle");

                    b.Property<double?>("VoltageSetpoint");

                    b.HasKey("ID");

                    b.ToTable("ExternalGrid");
                });

            modelBuilder.Entity("lite.Models.OverheadLine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EndNodeNo");

                    b.Property<double>("Length");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("StartNodeNo");

                    b.Property<double>("UnitaryCapacitance");

                    b.Property<double>("UnitaryReactance");

                    b.Property<double>("UnitaryResistance");

                    b.HasKey("ID");

                    b.ToTable("OverheadLine");
                });

            modelBuilder.Entity("lite.Models.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("lite.Models.TwoPhaseTransformer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("ApparentPowerRated");

                    b.Property<int>("HVNodeNo");

                    b.Property<double>("HVVoltageRated");

                    b.Property<int>("LVNodeNo");

                    b.Property<double>("LVVoltageRated");

                    b.Property<double>("LoadLossesRated");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("ShortCircuitVoltage");

                    b.HasKey("ID");

                    b.ToTable("TwoPhaseTransformer");
                });
#pragma warning restore 612, 618
        }
    }
}
